apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceApi.name}}
spec:
  selector:
    app: {{.Values.apiDeployment.name}}  # Seleciona os pods que correspondem a essa label
  ports:
    - name: http            # Nome da porta para referência interna (HTTP)
      protocol: TCP
      port: {{.Values.serviceApi.http.targetPort}}              # Porta externa do serviço Kubernetes
      targetPort: {{.Values.serviceApi.http.targetPort}}        # Porta no pod onde a sua aplicação está escutando
      {{- if eq .Values.environment "local" }}
      nodePort: {{ .Values.serviceApi.http.nodePort }}
      {{- end }}     
  type: {{ if eq .Values.environment "local" }} NodePort {{ else }} LoadBalancer {{ end }}
