# templates/deployment1.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: "{{ .Values.deployment.image }}"
        {{- if .Values.serviceAccount.create }}
        serviceAccountName: {{.Values.serviceAccount.name}}
        {{- end }}
        ports:
          - containerPort: 80   # Porta HTTP dentro do contêiner
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30  
          periodSeconds: 10        
          timeoutSeconds: 5        
          failureThreshold: 2     
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10  
          periodSeconds: 10        # Verifica a cada 10 segundos
          timeoutSeconds: 5        # Tempo limite de 5 segundos para a resposta
          failureThreshold: 2      # Número de falhas consecutivas para considerar o container como não pronto
        resources:
          requests:
            cpu: "512m"
            memory: "512Mi"
          limits:
            cpu: "2048m"
            memory: "2048Mi"
        env:  
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: AWS_REGION
          
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: AWS_REGION

          - name: AWS_SERVICE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: AWS_SERVICE_URL

          - name: AWS_QUEUE
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap.name }}
                key: AWS_QUEUE