{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.role | default "" }}
spec:
  automountServiceAccountToken: true
{{- end }}
