{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    eks.amazonaws.com/role-arn: |
      {{ .Values.serviceAccount.principalRole | default "" }}
      {{ .Values.serviceAccount.labRole | default "" }}
{{- end }}
