apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.configmap.name}}
data:
  AWS_REGION: "{{ .Values.aws.region }}"
  AWS_SERVICE_URL: "{{ .Values.aws.serviceUrl }}"
  AWS_QUEUE: "{{ .Values.aws.QueueUrl }}"


