apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.identityHpa.name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.identityDeployment.name}}
  minReplicas: {{.Values.identityHpa.minReplicas}}  # Número mínimo de réplicas
  maxReplicas: {{.Values.identityHpa.maxReplicas}}  # Número máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.identityHpa.cpuAverageUtilization}}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{.Values.identityHpa.memoryAverageUtilization}}
