apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.identityDeployment.name }}
spec:
  replicas: {{ .Values.identityDeployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.identityDeployment.name }}
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: {{ .Values.identityDeployment.name }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: api-service-account
      {{- end }}
      containers:
        - name: {{ .Values.identityDeployment.name }}
          image: "{{ .Values.identityDeployment.image }}"
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30  
            periodSeconds: 10        
            timeoutSeconds: 5        
            failureThreshold: 2     
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10  
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
          resources:
            requests:
              cpu: "512m"
              memory: "512Mi"
            limits:
              cpu: "2048m"
              memory: "2048Mi"
          env:  
            - name: ConnectionString
              valueFrom:
                configMapKeyRef:
                    name:  {{ .Values.configmap.name }}
                    key: ConnectionString
            - name: SecretKey
              valueFrom:
                configMapKeyRef:
                    name: {{ .Values.configmap.name }}
                    key: SecretKey