apiVersion: v1
kind: Service
metadata:
    name: localstack
spec:
    selector:
        app: localstack
    ports:
      - protocol: TCP
        port: 4566 # Porta que será acessada pelos outros pods
        targetPort: 4566 # Porta do container
    type: ClusterIP
