{{- if eq .Values.environment "local" }}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: localstack
spec:
    replicas: 1
    selector:
        matchLabels:
            app: localstack
    template:
        metadata:
            labels:
                app: localstack
        spec:
            containers:
              - name: localstack
                image: localstack/localstack:latest
                ports:
                  - containerPort: 4566
                resources:
                    requests:
                        memory: "1Gi"
                        cpu: "500m"
                    limits:
                        memory: "2Gi"
                        cpu: "1"
                volumeMounts:
                  - name: localstack-data
                    mountPath: /tmp/localstack-new-data # Diretório dentro do contêiner onde o volume será montado
            volumes:
              - name: localstack-data
                hostPath:
                    path: /Users/flaviorobertoteixeira/Desktop/Desenvolvimento/PosTech/Hackaton/processador-video-api/src/infra/localstack-volume # Caminho no nó do Kubernetes
                    type: DirectoryOrCreate # Cria o diretório caso não exista
{{- end }}
