{{- if eq .Values.environment "local" }}
apiVersion: v1
kind: Service
metadata:
    name: postgres
spec:
    selector:
        app: postgres
    ports:
      - protocol: TCP
        port: 5432 # Porta que será acessada pelos outros pods
        targetPort: 5432 # Porta do container
    type: ClusterIP
{{- end }}
