environment: local

ConnectionString: "Host=127.0.0.1;Port=5432;Pooling=true;Database=ProcessamentoImagemIdentity;User Id=postgres;"

aws:
  key: AwsIntegration
  region: "us-east-1"

deployment:
  name: api-deployment
  image: kenobirt/processamento-video.api:local
  replicas: 1

configmap:
  name: api-configmap

hpa:
  name: api-hpa
  minReplicas: 1
  maxReplicas: 2
  cpuAverageUtilization: 60
  memoryAverageUtilization: 60

service:
  name: api-svc
  http:
    targetPort: 80
    nodePort: 32000

serviceAccount:
  create: false
