environment: local

ConnectionString: "Host=127.0.0.1;Port=5432;Pooling=true;Database=ProcessamentoImagemIdentity;User Id=postgres;"

aws:
  key: ""
  region: "us-east-1"
  accessKey: ""
  secret: ""
  token: ""

deployment:
  name: api-deployment
  image: kenobirt/processamento-video.api:latest
  replicas: 1

configmap:
  name: api-configmap

hpa:
  name: api-hpa
  minReplicas: 1
  maxReplicas: 5
  cpuAverageUtilization: 50
  memoryAverageUtilization: 50

service:
  name: api-svc
  http:
    targetPort: 80
    nodePort: 32000

serviceAccount:
  create: false
