environment: local

ConnectionString: "Host=postgres;Port=5432;Pooling=true;Database=ProcessamentoImagemIdentity;User Id=postgres;Password=local123;"
SecretKey: "chave_token_secreta_muito_segura_de_128_bits!"

aws:
  key: ""
  region: "us-east-1"
  accessKey: ""
  secret: ""
  token: ""

apiDeployment:
  name: api-deployment
  image: kenobirt/processamento-video.gerenciador.api:latest
  replicas: 1

identityDeployment:
  name: identity-deployment
  image: kenobirt/processamento-video.identity.api:latest
  replicas: 1

conversorDeployment:
  name: conversor-deployment
  image: kenobirt/processamento-video.conversor.worker:latest
  replicas: 1

configmap:
  name: api-configmap

apiHpa:
  name: api-hpa
  minReplicas: 1
  maxReplicas: 5
  cpuAverageUtilization: 50
  memoryAverageUtilization: 50

identityHpa:
  name: identity-hpa
  minReplicas: 1
  maxReplicas: 5
  cpuAverageUtilization: 50
  memoryAverageUtilization: 50

conversorHpa:
  name: conversor-worker-hpa
  minReplicas: 1
  maxReplicas: 5
  cpuAverageUtilization: 50
  memoryAverageUtilization: 50

serviceApi:
  name: api-svc
  http:
    targetPort: 80
    nodePort: 32000

serviceIdentity:
  name: identity-svc
  http:
    targetPort: 80
    nodePort: 32001

serviceAccount:
  create: false
