name: Deploy AWS - EKS

on:
  push:
    branches:
    - main

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "processador-video-cluster"

jobs:
  deploy:
    name: Deploy AWS
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: AWS Configure
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.REGION_DEFAULT }}

    - name: Update Kube Config
      run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION_DEFAULT }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm version --short  # Verificar versão do Helm instalada

    - name: Deploy with Helm
      run: |
        helm upgrade --install processador-video ./infra/processamentovideo-chart -f ./infra/values-production.yaml \
          --set aws.accesKey="${{ secrets.AWS_ACCESS_KEY }}"
          --set aws.secretKey="${{ secrets.AWS_SECRET_KEY }}"
          --set api.configmap.database.value="${{ secrets.DB_CONNECTION }}" \
          --set "forceUpdate=$(date +%s)"
