name: Publish Docker Image to development

on:
  push:
    branches:
    - develop

permissions:
  pull-requests: write

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:

    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }} # Checkout para a branch atual

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore  src/app/ProcessadorVideo/ProcessadorVideo.sln

    - name: Build the project
      run: dotnet build --no-restore --configuration Release  src/app/ProcessadorVideo/ProcessadorVideo.sln

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal  src/app/ProcessadorVideo/ProcessadorVideo.sln

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/processamento-video.api:latest .
      working-directory: src/app/ProcessadorVideo # Path to your Dockerfile

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/processamento-video.api:latest
