name: .NET Build and Test Workflow

on:
  push:
    branches:
    - feature**

permissions:
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }} # Checkout para a branch atual

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x' # Use a versão mais recente do .NET 7.0 disponível

    - name: Install dependencies
      run: dotnet restore  src/app/ProcessadorVideo/ProcessadorVideo.sln

    - name: Build the project
      run: dotnet build --no-restore --configuration Release  src/app/ProcessadorVideo/ProcessadorVideo.sln

    - name: Run tests
      run: dotnet test --no-build --configuration Release --verbosity normal  src/app/ProcessadorVideo/ProcessadorVideo.sln

# name: Create Infra AWS

# on:
#   push:
#     branches:
#     - feature**

# env:
#   REGION_DEFAULT: us-east-1

# jobs:
#   create_infra:
#     name: terraform
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout
#       uses: actions/checkout@v2

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
#         aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
#         aws-region: ${{ env.REGION_DEFAULT }}

#     - name: Terraform Setup
#       uses: hashicorp/setup-terraform@v3
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

#     - name: Terraform Format
#       id: fmt
#       run: terraform fmt -check
#       continue-on-error: true

#     - name: Terraform Init
#       id: init
#       run: terraform init -input=false

#     - name: Terraform Validate
#       id: validate
#       run: terraform validate -no-color

#     - name: Terraform Plan
#       id: plan
#       run: terraform plan -out=tfplan -no-color -input=false
#       continue-on-error: true
