name: Deploy AWS - EKS

on:
  push:
    branches:
    - main

env:
  REGION_DEFAULT: "us-east-1"
  CLUSTER_NAME: "processador-video-cluster"

jobs:
  deploy-terraform:
    name: terraform
    runs-on: ubuntu-latest
    needs: publish-image

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Terraform Setup
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: terraform init -input=false
      working-directory: ./src/infra

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./src/infra

    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan -no-color -input=false
      continue-on-error: false
      working-directory: ./src/infra

    - name: Terraform Apply
      id: apply
      run: terraform apply -input=false -auto-approve
      working-directory: ./src/infra
